language: minimal
sudo: false

branches:
  except:
  - /.*gh-pages.*/


notifications:
  email:
     recipients:
       - nickpapior@gmail.com
     on_failure: always
     on_success: change

matrix:
  include:
   - env:
     - CONDA_ENV=py27
   - env:
     - CONDA_ENV=py36


before_install:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
# Do actual package installations
  - conda update -q conda
  - conda info -a


install:
  - conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml
  - source activate test_env
  - conda list
  - pip install --no-deps -e .


script:
  - which python
  - python --version
  - python -OO -c "import Inelastica"
  - Inelastica --help
